"""The mew C++ core (Google Benchmark bindings)."""

import enum
import types
from collections.abc import Callable, Sequence

BENCHMARK_COMMIT: str = "83c826c8d9499bb3ecd02f6f4abbac1e990297fe"

BENCHMARK_VERSION: str = "v1.9.5"

class TimeUnit(enum.Enum):
    ns = 0

    us = 1

    ms = 2

    s = 3

class RunType(enum.Enum):
    iteration = 0

    aggregate = 1

class BenchmarkName:
    @property
    def function_name(self) -> str: ...
    @property
    def args(self) -> str: ...
    @property
    def min_time(self) -> str: ...
    @property
    def min_warmup_time(self) -> str: ...
    @property
    def iterations(self) -> str: ...
    @property
    def repetitions(self) -> str: ...
    @property
    def time_type(self) -> str: ...
    @property
    def threads(self) -> str: ...
    def __str__(self) -> str: ...

class Run:
    """
    A single benchmark run report. Times are in seconds (accumulated across iterations); use `adjusted_real_time()` for per-iteration averages.
    """

    @property
    def run_name(self) -> BenchmarkName: ...
    def benchmark_name(self) -> str: ...
    @property
    def family_index(self) -> int: ...
    @property
    def per_family_instance_index(self) -> int: ...
    @property
    def run_type(self) -> RunType: ...
    @property
    def aggregate_name(self) -> str: ...
    @property
    def report_label(self) -> str: ...
    @property
    def skip_message(self) -> str: ...
    @property
    def iterations(self) -> int: ...
    @property
    def threads(self) -> int: ...
    @property
    def repetition_index(self) -> int: ...
    @property
    def repetitions(self) -> int: ...
    @property
    def time_unit(self) -> TimeUnit: ...
    @property
    def real_accumulated_time(self) -> float: ...
    @property
    def cpu_accumulated_time(self) -> float: ...
    def adjusted_real_time(self) -> float: ...
    def adjusted_cpu_time(self) -> float: ...
    @property
    def complexity_n(self) -> int: ...
    @property
    def counters(self) -> dict: ...
    @property
    def skipped(self) -> bool: ...

def run_benchmarks(argv: Sequence[str], reporter: object | None = None) -> int:
    """
    Initialize Google Benchmark with `argv`, run all registered benchmarks, then clear the registry. Returns the number of benchmarks run. Pass a Fanout reporter from Python to multiplex into multiple sinks.
    """

class PauseScope:
    """Context manager that pauses State timing within a scope."""

    def __enter__(self) -> PauseScope: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

class State:
    """
    Active microbenchmark state. Iterate with `for _ in state:` to time the body.
    """

    def __iter__(self) -> State: ...
    def __next__(self) -> None: ...
    def pause(self) -> PauseScope:
        """
        Return a context manager that pauses timing for the duration of the `with` block.
        """

    def skip_with_error(self, msg: str) -> None: ...
    def skip_with_message(self, msg: str) -> None: ...
    def set_label(self, label: str) -> None: ...
    def set_iteration_time(self, seconds: float) -> None: ...
    def set_items_processed(self, items: int) -> None: ...
    def set_bytes_processed(self, n_bytes: int) -> None: ...
    def set_counter(self, name: str, value: float) -> None: ...
    def range(self, pos: int = 0) -> int: ...
    @property
    def range_size(self) -> int: ...
    @property
    def iterations(self) -> int: ...
    @property
    def threads(self) -> int: ...
    @property
    def thread_index(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def skipped(self) -> bool: ...
    @property
    def error_occurred(self) -> bool: ...
    @property
    def max_iterations(self) -> int: ...

class BenchmarkHandle:
    """
    Handle to a registered Google Benchmark. Methods return the same handle so options can be chained.
    """

    def min_time(self, seconds: float) -> BenchmarkHandle: ...
    def min_warmup_time(self, seconds: float) -> BenchmarkHandle: ...
    def iterations(self, n: int) -> BenchmarkHandle: ...
    def repetitions(self, n: int) -> BenchmarkHandle: ...
    def unit(self, unit: str) -> BenchmarkHandle: ...
    def use_real_time(self) -> BenchmarkHandle: ...
    def use_manual_time(self) -> BenchmarkHandle: ...
    def measure_process_cpu_time(self) -> BenchmarkHandle: ...
    def report_aggregates_only(self, value: bool = True) -> BenchmarkHandle: ...
    def display_aggregates_only(self, value: bool = True) -> BenchmarkHandle: ...
    @property
    def name(self) -> str: ...

def register_benchmark(name: str, fn: Callable) -> BenchmarkHandle:
    """
    Register `fn` as a benchmark under `name` and return a chainable handle.
    """

def clear_registered_benchmarks() -> None:
    """Drop all previously registered benchmarks from the global registry."""
